# Generated by Django 2.1 on 2019-03-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190311_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='submissions',
            field=models.ManyToManyField(blank=True, related_name='categories', to='main.Team'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='table',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
