# Generated by Django 2.1 on 2019-03-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190312_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
