# Generated by Django 2.1 on 2019-03-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_is_opt_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='can_anyone_judge',
            field=models.BooleanField(default=False),
        ),
    ]
