# Generated by Django 2.1 on 2019-03-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_can_anyone_judge'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='min_judges',
            field=models.IntegerField(default=1, help_text='The minimum number of judges a team should be seen by for this category'),
        ),
    ]
