# Generated by Django 2.1 on 2019-03-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_event_organizers'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='est_time_per_demo',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=3),
        ),
        migrations.AddField(
            model_name='event',
            name='max_judges_per_sponsor_category',
            field=models.IntegerField(default=99),
        ),
        migrations.AddField(
            model_name='event',
            name='min_judges_per_team',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='time_limit',
            field=models.IntegerField(default=120),
        ),
    ]
