# Generated by Django 2.1 on 2019-03-15 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190314_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='judges',
            field=models.ManyToManyField(blank=True, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
